# vingroto shell completions for nushell
# Generated by vingroto completions nushell; do not edit by hand.

export extern vingroto []

def "nu-complete vingroto api operation" [] {
  [
    "account.create"
    "account.discover"
    "account.reorder"
    "account.update"
    "account.username"
    "draft.delete"
    "draft.list"
    "draft.save"
    "event.subscribe"
    "mailbox.setMuted"
    "mailbox.snapshot"
    "message.body"
    "message.get"
    "message.list"
    "message.move"
    "message.setSeen"
    "outbox.cancel"
    "outbox.enqueue"
    "outbox.list"
    "outbox.release"
    "search.marks"
    "search.messages"
    "search.start"
    "server.health"
    "server.status"
    "settings.saveEditor"
    "settings.saveNotifications"
    "settings.saveSend"
    "settings.saveSyncSettings"
    "sync.run"
    "delete"
    "get"
    "head"
    "options"
    "patch"
    "post"
    "put"
  ]
}

def "nu-complete vingroto api path" [] {
  [
    "/api/accounts"
    "/api/accounts/discover"
    "/api/accounts/order"
    "/api/accounts/{accountId}"
    "/api/accounts/{accountId}/username"
    "/api/drafts"
    "/api/drafts/{draftId}"
    "/api/events"
    "/api/health"
    "/api/mailboxes"
    "/api/mailboxes/{mailboxId}/muted"
    "/api/messages"
    "/api/messages/move"
    "/api/messages/seen"
    "/api/messages/{messageId}"
    "/api/messages/{messageId}/body"
    "/api/outbox"
    "/api/outbox/{outboxId}/cancel"
    "/api/outbox/{outboxId}/release"
    "/api/search/marks"
    "/api/search/messages"
    "/api/search/start"
    "/api/settings/editor"
    "/api/settings/notifications"
    "/api/settings/send"
    "/api/settings/sync"
    "/api/status"
    "/api/sync"
  ]
}

def "nu-complete vingroto api flag param" [] {
  [
    "accountId="
    "draftId="
    "limit="
    "mailboxId="
    "messageId="
    "outboxId="
    "query="
    "scope=all"
    "scope=mailbox"
    "scope=unread"
  ]
}

export extern "vingroto api" [
  --param: string@"nu-complete vingroto api flag param" # Path or query parameter for an operation, as name=value
  --data(-d): string # Request body, @file to read a file, or - to read stdin
  --header(-H): string # Request header in name:value form
  --server: string # Daemon base URL (defaults to VINGROTO_SERVER or the registration file)
  --token: string # Daemon bearer token (defaults to VINGROTO_TOKEN or the token file)
  operation?: string@"nu-complete vingroto api operation" # OpenAPI operation ID, or an HTTP method followed by a request path
  path?: string@"nu-complete vingroto api path" # Request path, when the first argument is an HTTP method
]

def "nu-complete vingroto api describe operation" [] {
  [
    "account.create"
    "account.discover"
    "account.reorder"
    "account.update"
    "account.username"
    "draft.delete"
    "draft.list"
    "draft.save"
    "event.subscribe"
    "mailbox.setMuted"
    "mailbox.snapshot"
    "message.body"
    "message.get"
    "message.list"
    "message.move"
    "message.setSeen"
    "outbox.cancel"
    "outbox.enqueue"
    "outbox.list"
    "outbox.release"
    "search.marks"
    "search.messages"
    "search.start"
    "server.health"
    "server.status"
    "settings.saveEditor"
    "settings.saveNotifications"
    "settings.saveSend"
    "settings.saveSyncSettings"
    "sync.run"
  ]
}

export extern "vingroto api describe" [
  operation: string@"nu-complete vingroto api describe operation" # OpenAPI operation ID to describe
]

export extern "vingroto api list" []

def "nu-complete vingroto completions shell" [] {
  [
    "bash"
    "nushell"
    "zsh"
  ]
}

export extern "vingroto completions" [
  shell: string@"nu-complete vingroto completions shell" # Shell to print completions for
]

