# vingroto shell completions for nushell
# Generated by vingroto completions nushell; do not edit by hand.

export extern vingroto []

def "nu-complete vingroto api operation" [] {
  [
    "account.create"
    "account.discover"
    "account.update"
    "account.username"
    "event.subscribe"
    "mailbox.setMuted"
    "mailbox.snapshot"
    "message.body"
    "message.get"
    "message.list"
    "message.move"
    "message.setSeen"
    "search.marks"
    "search.messages"
    "search.start"
    "server.health"
    "server.status"
    "settings.saveNotifications"
    "settings.saveSyncSettings"
    "sync.run"
    "delete"
    "get"
    "head"
    "options"
    "patch"
    "post"
    "put"
  ]
}

export extern "vingroto api" [
  --param: string # OpenAPI path or query parameter
  --data(-d): string # Request body
  --header(-H): string # Request header in name:value form
  --server: string # Daemon base URL (defaults to VINGROTO_SERVER or the registration file)
  --token: string # Daemon bearer token (defaults to VINGROTO_TOKEN or the token file)
  ...operation: string@"nu-complete vingroto api operation" # OpenAPI operation ID, or an HTTP method followed by a path
]

def "nu-complete vingroto completions shell" [] {
  [
    "bash"
    "nushell"
    "zsh"
  ]
}

export extern "vingroto completions" [
  shell: string@"nu-complete vingroto completions shell" # Shell to print completions for
]

