[[language]]
name = "python"
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"]}
auto-format = true

[language.config.pylsp.plugins]
ruff = { enabled = true }
mypy = { enabled= true }
