[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "yarn", args = ["run", "prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "yarn", args = ["run", "prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]       
name = "python"
language-servers = [ "pylsp" ]
formatter = { command = "black", args = ["--quiet", "-"] }
         
[language-server.pylsp.config.plugins]
pylsp-mypy = {enabled = false, live_mode = true, strict = false}
ruff = { enabled = false, ignore = ["F401"], lineLength = 120 }                                                  

