[[language]]
name = "ts"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "python"
formatter = { command = "sh", args = ["-c", "black --quiet - | isort -"]}
auto-format = true
config.pylsp.plugins.ruff = { enabled = true }
config.pylsp.plugins.mypy = { enabled = true }

