[[language]]
name = "rust"
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "yarn", args = ["run", "prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "yarn", args = ["run", "prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

